version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip awscli boto3 jq
      - aws --version

  pre_build:
    commands:
      - echo "=== PRE-BUILD PHASE ==="
      - echo "Source Account ID:" $AWS_ACCOUNT_ID
      - echo "Target Account ID:" $TARGET_ACCOUNT_ID
      - echo "Cross Account Role:" $CROSS_ACCOUNT_ROLE_NAME
      - echo "Environment:" $ENVIRONMENT
      - echo "Region:" $AWS_DEFAULT_REGION
      
      - echo "Validating CloudFormation templates..."
      - aws cloudformation validate-template --template-body file://templates/infrastructure/vpc.yaml
      - aws cloudformation validate-template --template-body file://templates/infrastructure/security-groups.yaml
      - aws cloudformation validate-template --template-body file://templates/infrastructure/s3-storage.yaml
      - echo "All templates validated successfully"

  build:
    commands:
      - echo "=== BUILD PHASE ==="
      - mkdir -p packaged-templates
      
      - echo "Copying CloudFormation templates..."
      - cp templates/infrastructure/*.yaml packaged-templates/
      - ls -la packaged-templates/
      
      - echo "Assuming cross-account deployment role..."
      - CROSS_ACCOUNT_ROLE_ARN="arn:aws:iam::${TARGET_ACCOUNT_ID}:role/${CROSS_ACCOUNT_ROLE_NAME}"
      - echo "Role ARN:" $CROSS_ACCOUNT_ROLE_ARN
      
      - TEMP_ROLE=$(aws sts assume-role --role-arn $CROSS_ACCOUNT_ROLE_ARN --role-session-name "CrossAccount-Deploy-$(date +%s)" --external-id $EXTERNAL_ID --duration-seconds 3600)
      - export AWS_ACCESS_KEY_ID=$(echo $TEMP_ROLE | jq -r '.Credentials.AccessKeyId')
      - export AWS_SECRET_ACCESS_KEY=$(echo $TEMP_ROLE | jq -r '.Credentials.SecretAccessKey')
      - export AWS_SESSION_TOKEN=$(echo $TEMP_ROLE | jq -r '.Credentials.SessionToken')
      
      - echo "Verifying assumed role identity..."
      - aws sts get-caller-identity
      
      - echo "Deploying VPC infrastructure..."
      - aws cloudformation deploy --template-file packaged-templates/vpc.yaml --stack-name CrossAccount-VPC-${ENVIRONMENT} --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM --parameter-overrides Environment=${ENVIRONMENT} Project=CrossAccountInfraDeployment --tags Environment=${ENVIRONMENT} Project=CrossAccountInfraDeployment ManagedBy=CodePipeline --no-fail-on-empty-changeset --region $AWS_DEFAULT_REGION
      
      - echo "Deploying Security Groups..."
      - aws cloudformation deploy --template-file packaged-templates/security-groups.yaml --stack-name CrossAccount-SecurityGroups-${ENVIRONMENT} --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM --parameter-overrides Environment=${ENVIRONMENT} Project=CrossAccountInfraDeployment VPCStackName=CrossAccount-VPC-${ENVIRONMENT} --tags Environment=${ENVIRONMENT} Project=CrossAccountInfraDeployment ManagedBy=CodePipeline --no-fail-on-empty-changeset --region $AWS_DEFAULT_REGION
      
      - echo "Deploying S3 Storage..."
      - aws cloudformation deploy --template-file packaged-templates/s3-storage.yaml --stack-name CrossAccount-S3Storage-${ENVIRONMENT} --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM --parameter-overrides Environment=${ENVIRONMENT} Project=CrossAccountInfraDeployment VPCStackName=CrossAccount-VPC-${ENVIRONMENT} --tags Environment=${ENVIRONMENT} Project=CrossAccountInfraDeployment ManagedBy=CodePipeline --no-fail-on-empty-changeset --region $AWS_DEFAULT_REGION

  post_build:
    commands:
      - echo "=== POST-BUILD PHASE ==="
      - echo "Deployment completed successfully!"
      
      - echo "Listing deployed stacks..."
      - aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE UPDATE_COMPLETE --query 'StackSummaries[?contains(StackName, `CrossAccount`)].{Name:StackName,Status:StackStatus}' --output table
      
      - echo "=== DEPLOYMENT SUMMARY ==="
      - echo "All resources created in target account:" $TARGET_ACCOUNT_ID
      - echo "Environment:" $ENVIRONMENT
      - echo "Region:" $AWS_DEFAULT_REGION

artifacts:
  files:
    - 'packaged-templates/**/*'
  name: CrossAccountInfraDeploymentArtifacts