AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 storage infrastructure for cross-account deployment'

Parameters:
  Environment:
    Type: String
    Default: 'production'
    AllowedValues: ['development', 'staging', 'production']
    Description: 'Environment name'
    
  Project:
    Type: String
    Default: 'CrossAccountInfraDeployment'
    Description: 'Project name for resource tagging'
    
  VPCStackName:
    Type: String
    Default: 'CrossAccount-VPC-production'
    Description: 'Name of the VPC CloudFormation stack'
    
  EnableVersioning:
    Type: String
    Default: 'true'
    AllowedValues: ['true', 'false']
    Description: 'Enable S3 bucket versioning'
    
  EnableLogging:
    Type: String
    Default: 'true'
    AllowedValues: ['true', 'false']
    Description: 'Enable S3 access logging'

Conditions:
  EnableS3Versioning: !Equals [!Ref EnableVersioning, 'true']
  EnableS3Logging: !Equals [!Ref EnableLogging, 'true']
  IsProduction: !Equals [!Ref Environment, 'production']

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Project Configuration"
        Parameters:
          - Environment
          - Project
          - VPCStackName
      - Label:
          default: "S3 Configuration"
        Parameters:
          - EnableVersioning
          - EnableLogging

Resources:
  # Application Data Bucket
  ApplicationDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${Project}-${Environment}-app-data-${AWS::AccountId}-${AWS::Region}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
            BucketKeyEnabled: true
      VersioningConfiguration:
        Status: !If [EnableS3Versioning, 'Enabled', 'Suspended']
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: GLACIER
              - TransitionInDays: 365
                StorageClass: DEEP_ARCHIVE
          - Id: DeleteOldVersions
            Status: !If [EnableS3Versioning, 'Enabled', 'Disabled']
            NoncurrentVersionExpirationInDays: 90
          - Id: DeleteIncompleteMultipartUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
      LoggingConfiguration: !If
        - EnableS3Logging
        - DestinationBucketName: !Ref AccessLogsBucket
          LogFilePrefix: 'access-logs/application-data/'
        - !Ref 'AWS::NoValue'
      NotificationConfiguration:
        CloudWatchConfigurations:
          - Event: 's3:ObjectCreated:*'
      IntelligentTieringConfigurations:
        - Id: IntelligentTiering
          Status: Enabled
          OptionalFields:
            - BucketKeyStatus
      Tags:
        - Key: Name
          Value: !Sub '${Project}-${Environment}-ApplicationData'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref Project
        - Key: Purpose
          Value: ApplicationData
        - Key: ManagedBy
          Value: CloudFormation

  # Access Logs Bucket
  AccessLogsBucket:
    Type: AWS::S3::Bucket
    Condition: EnableS3Logging
    Properties:
      BucketName: !Sub '${Project}-${Environment}-access-logs-${AWS::AccountId}-${AWS::Region}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
            BucketKeyEnabled: true
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldLogs
            Status: Enabled
            ExpirationInDays: 90
          - Id: TransitionLogsToIA
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 60
                StorageClass: GLACIER
      Tags:
        - Key: Name
          Value: !Sub '${Project}-${Environment}-AccessLogs'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref Project
        - Key: Purpose
          Value: AccessLogs
        - Key: ManagedBy
          Value: CloudFormation

  # Backup Bucket
  BackupBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${Project}-${Environment}-backup-${AWS::AccountId}-${AWS::Region}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
            BucketKeyEnabled: true
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldBackups
            Status: Enabled
            NoncurrentVersionExpirationInDays: 365
          - Id: TransitionBackupsToGlacier
            Status: Enabled
            Transitions:
              - TransitionInDays: 1
                StorageClass: STANDARD_IA
              - TransitionInDays: 30
                StorageClass: GLACIER
              - TransitionInDays: 90
                StorageClass: DEEP_ARCHIVE
      Tags:
        - Key: Name
          Value: !Sub '${Project}-${Environment}-Backup'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref Project
        - Key: Purpose
          Value: Backup
        - Key: ManagedBy
          Value: CloudFormation

  # Static Website Bucket (for web assets)
  StaticWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${Project}-${Environment}-static-website-${AWS::AccountId}-${AWS::Region}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
            BucketKeyEnabled: true
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, HEAD]
            AllowedOrigins: ['*']
            MaxAge: 3600
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldAssets
            Status: Enabled
            ExpirationInDays: 365
      Tags:
        - Key: Name
          Value: !Sub '${Project}-${Environment}-StaticWebsite'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref Project
        - Key: Purpose
          Value: StaticWebsite
        - Key: ManagedBy
          Value: CloudFormation

  # CloudWatch Log Group for S3 events
  S3EventsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/s3/${Project}-${Environment}'
      RetentionInDays: 30
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref Project
        - Key: Purpose
          Value: S3Events

  # IAM Role for S3 Cross-Region Replication
  S3ReplicationRole:
    Type: AWS::IAM::Role
    Condition: IsProduction
    Properties:
      RoleName: !Sub '${Project}-${Environment}-S3-Replication-Role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: S3ReplicationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObjectVersionForReplication'
                  - 's3:GetObjectVersionAcl'
                  - 's3:GetObjectVersionTagging'
                Resource: !Sub '${ApplicationDataBucket}/*'
              - Effect: Allow
                Action:
                  - 's3:ListBucket'
                Resource: !Ref ApplicationDataBucket
              - Effect: Allow
                Action:
                  - 's3:ReplicateObject'
                  - 's3:ReplicateDelete'
                  - 's3:ReplicateTags'
                Resource: !Sub '${BackupBucket}/*'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref Project
        - Key: Purpose
          Value: S3Replication

  # Bucket Policy for Application Data Bucket
  ApplicationDataBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ApplicationDataBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # Deny insecure connections
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub '${ApplicationDataBucket}'
              - !Sub '${ApplicationDataBucket}/*'
            Condition:
              Bool:
                'aws:SecureTransport': 'false'
          # Allow access from VPC endpoints only
          - Sid: AllowVPCEndpointAccess
            Effect: Allow
            Principal: '*'
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
              - 's3:DeleteObject'
              - 's3:ListBucket'
            Resource:
              - !Sub '${ApplicationDataBucket}'
              - !Sub '${ApplicationDataBucket}/*'
            Condition:
              StringEquals:
                'aws:SourceVpce':
                  Fn::ImportValue: !Sub '${VPCStackName}-S3-VPC-Endpoint'

  # Bucket Policy for Static Website Bucket
  StaticWebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticWebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # Allow public read access for website content
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${StaticWebsiteBucket}/*'
          # Deny insecure connections
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub '${StaticWebsiteBucket}'
              - !Sub '${StaticWebsiteBucket}/*'
            Condition:
              Bool:
                'aws:SecureTransport': 'false'

  # Bucket Policy for Access Logs Bucket
  AccessLogsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: EnableS3Logging
    Properties:
      Bucket: !Ref AccessLogsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # Deny insecure connections
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub '${AccessLogsBucket}'
              - !Sub '${AccessLogsBucket}/*'
            Condition:
              Bool:
                'aws:SecureTransport': 'false'
          # Allow S3 service to write access logs
          - Sid: AllowS3ServiceLogs
            Effect: Allow
            Principal:
              Service: logging.s3.amazonaws.com
            Action: 's3:PutObject'
            Resource: !Sub '${AccessLogsBucket}/access-logs/*'
            Condition:
              ArnEquals:
                'aws:SourceArn': !Sub '${ApplicationDataBucket}'

  # CloudWatch Alarm for unusual S3 activity
  S3UnusualActivityAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${Project}-${Environment}-S3-Unusual-Activity'
      AlarmDescription: 'Alarm for unusual S3 activity patterns'
      MetricName: NumberOfObjects
      Namespace: AWS/S3
      Statistic: Sum
      Period: 3600
      EvaluationPeriods: 2
      Threshold: 10000
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: BucketName
          Value: !Ref ApplicationDataBucket
        - Name: StorageType
          Value: AllStorageTypes
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref S3AlertsTopic
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref Project

  # SNS Topic for S3 alerts
  S3AlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${Project}-${Environment}-S3-Alerts'
      DisplayName: 'S3 Storage Alerts'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref Project

  # Lambda function for S3 event processing
  S3EventProcessorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${Project}-${Environment}-S3-Event-Processor'
      Runtime: python3.9
      Handler: index.lambda_handler
      Role: !GetAtt S3EventProcessorRole.Arn
      Code:
        ZipFile: |
          import json
          import boto3
          import logging
          
          logger = logging.getLogger()
          logger.setLevel(logging.INFO)
          
          def lambda_handler(event, context):
              """Process S3 events and log them to CloudWatch"""
              
              for record in event['Records']:
                  bucket = record['s3']['bucket']['name']
                  key = record['s3']['object']['key']
                  event_name = record['eventName']
                  
                  logger.info(f"S3 Event: {event_name} on {bucket}/{key}")
                  
                  # Add custom processing logic here
                  # For example: virus scanning, metadata extraction, etc.
              
              return {
                  'statusCode': 200,
                  'body': json.dumps('S3 events processed successfully')
              }
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          PROJECT: !Ref Project
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref Project

  # IAM Role for S3 Event Processor Lambda
  S3EventProcessorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: S3EventProcessorPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:GetObjectVersion'
                Resource:
                  - !Sub '${ApplicationDataBucket}/*'
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'

Outputs:
  ApplicationDataBucketName:
    Description: 'Name of the application data S3 bucket'
    Value: !Ref ApplicationDataBucket
    Export:
      Name: !Sub '${AWS::StackName}-ApplicationDataBucket'

  ApplicationDataBucketArn:
    Description: 'ARN of the application data S3 bucket'
    Value: !GetAtt ApplicationDataBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ApplicationDataBucketArn'

  ApplicationDataBucketDomainName:
    Description: 'Domain name of the application data bucket'
    Value: !GetAtt ApplicationDataBucket.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-ApplicationDataBucketDomain'

  AccessLogsBucketName:
    Condition: EnableS3Logging
    Description: 'Name of the access logs S3 bucket'
    Value: !Ref AccessLogsBucket
    Export:
      Name: !Sub '${AWS::StackName}-AccessLogsBucket'

  BackupBucketName:
    Description: 'Name of the backup S3 bucket'
    Value: !Ref BackupBucket
    Export:
      Name: !Sub '${AWS::StackName}-BackupBucket'

  StaticWebsiteBucketName:
    Description: 'Name of the static website S3 bucket'
    Value: !Ref StaticWebsiteBucket
    Export:
      Name: !Sub '${AWS::StackName}-StaticWebsiteBucket'

  StaticWebsiteBucketWebsiteURL:
    Description: 'Website URL of the static website bucket'
    Value: !GetAtt StaticWebsiteBucket.WebsiteURL
    Export:
      Name: !Sub '${AWS::StackName}-StaticWebsiteURL'

  S3ReplicationRoleArn:
    Condition: IsProduction
    Description: 'ARN of the S3 replication role'
    Value: !GetAtt S3ReplicationRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-S3ReplicationRole'

  S3EventsLogGroupName:
    Description: 'Name of the CloudWatch log group for S3 events'
    Value: !Ref S3EventsLogGroup
    Export:
      Name: !Sub '${AWS::StackName}-S3EventsLogGroup'

  S3AlertsTopicArn:
    Description: 'ARN of the SNS topic for S3 alerts'
    Value: !Ref S3AlertsTopic
    Export:
      Name: !Sub '${AWS::StackName}-S3AlertsTopic'

  S3EventProcessorFunctionArn:
    Description: 'ARN of the S3 event processor Lambda function'
    Value: !GetAtt S3EventProcessorFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-S3EventProcessorFunction'