AWSTemplateFormatVersion: '2010-09-09'
Description: 'Security Groups for cross-account infrastructure deployment'

Parameters:
  Environment:
    Type: String
    Default: 'production'
    AllowedValues: ['development', 'staging', 'production']
    Description: 'Environment name'
    
  Project:
    Type: String
    Default: 'CrossAccountInfraDeployment'
    Description: 'Project name for resource tagging'
    
  VPCStackName:
    Type: String
    Default: 'CrossAccount-VPC-production'
    Description: 'Name of the VPC CloudFormation stack'

Resources:
  # Application Load Balancer Security Group
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${Project}-${Environment}-ALB-SG'
      GroupDescription: 'Security group for Application Load Balancer'
      VpcId:
        Fn::ImportValue: !Sub '${VPCStackName}-VPC-ID'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: 'HTTP from internet'
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: 'HTTPS from internet'
      Tags:
        - Key: Name
          Value: !Sub '${Project}-${Environment}-ALB-SG'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref Project

  # Web Application Security Group
  WebAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${Project}-${Environment}-WebApp-SG'
      GroupDescription: 'Security group for web application servers'
      VpcId:
        Fn::ImportValue: !Sub '${VPCStackName}-VPC-ID'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ALBSecurityGroup
          Description: 'HTTP from ALB'
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourceSecurityGroupId: !Ref ALBSecurityGroup
          Description: 'HTTPS from ALB'
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupId: !Ref ALBSecurityGroup
          Description: 'Custom app port from ALB'
      Tags:
        - Key: Name
          Value: !Sub '${Project}-${Environment}-WebApp-SG'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref Project

  # Database Security Group
  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${Project}-${Environment}-Database-SG'
      GroupDescription: 'Security group for database servers'
      VpcId:
        Fn::ImportValue: !Sub '${VPCStackName}-VPC-ID'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref WebAppSecurityGroup
          Description: 'MySQL from web application'
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref WebAppSecurityGroup
          Description: 'PostgreSQL from web application'
      Tags:
        - Key: Name
          Value: !Sub '${Project}-${Environment}-Database-SG'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref Project

  # Bastion Host Security Group
  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${Project}-${Environment}-Bastion-SG'
      GroupDescription: 'Security group for bastion host'
      VpcId:
        Fn::ImportValue: !Sub '${VPCStackName}-VPC-ID'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: 'SSH from internet'
      Tags:
        - Key: Name
          Value: !Sub '${Project}-${Environment}-Bastion-SG'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref Project

  # Cache Security Group
  CacheSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${Project}-${Environment}-Cache-SG'
      GroupDescription: 'Security group for cache servers (Redis/Memcached)'
      VpcId:
        Fn::ImportValue: !Sub '${VPCStackName}-VPC-ID'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          SourceSecurityGroupId: !Ref WebAppSecurityGroup
          Description: 'Redis from web application'
        - IpProtocol: tcp
          FromPort: 11211
          ToPort: 11211
          SourceSecurityGroupId: !Ref WebAppSecurityGroup
          Description: 'Memcached from web application'
      Tags:
        - Key: Name
          Value: !Sub '${Project}-${Environment}-Cache-SG'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref Project

  # EFS Security Group
  EFSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${Project}-${Environment}-EFS-SG'
      GroupDescription: 'Security group for EFS file system'
      VpcId:
        Fn::ImportValue: !Sub '${VPCStackName}-VPC-ID'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 2049
          ToPort: 2049
          SourceSecurityGroupId: !Ref WebAppSecurityGroup
          Description: 'NFS from web application'
      Tags:
        - Key: Name
          Value: !Sub '${Project}-${Environment}-EFS-SG'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref Project

  # Lambda Security Group
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${Project}-${Environment}-Lambda-SG'
      GroupDescription: 'Security group for Lambda functions'
      VpcId:
        Fn::ImportValue: !Sub '${VPCStackName}-VPC-ID'
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: 'HTTPS for AWS API calls'
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: 'HTTP for external APIs'
      Tags:
        - Key: Name
          Value: !Sub '${Project}-${Environment}-Lambda-SG'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref Project

  # ECS Security Group
  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${Project}-${Environment}-ECS-SG'
      GroupDescription: 'Security group for ECS containers'
      VpcId:
        Fn::ImportValue: !Sub '${VPCStackName}-VPC-ID'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ALBSecurityGroup
          Description: 'HTTP from ALB'
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8999
          SourceSecurityGroupId: !Ref ALBSecurityGroup
          Description: 'Custom app ports from ALB'
      Tags:
        - Key: Name
          Value: !Sub '${Project}-${Environment}-ECS-SG'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref Project

Outputs:
  ALBSecurityGroupId:
    Description: 'ID of the ALB Security Group'
    Value: !Ref ALBSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-ALB-SG-ID'

  WebAppSecurityGroupId:
    Description: 'ID of the Web Application Security Group'
    Value: !Ref WebAppSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-WebApp-SG-ID'

  DatabaseSecurityGroupId:
    Description: 'ID of the Database Security Group'
    Value: !Ref DatabaseSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-Database-SG-ID'

  BastionSecurityGroupId:
    Description: 'ID of the Bastion Security Group'
    Value: !Ref BastionSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-Bastion-SG-ID'

  CacheSecurityGroupId:
    Description: 'ID of the Cache Security Group'
    Value: !Ref CacheSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-Cache-SG-ID'

  EFSSecurityGroupId:
    Description: 'ID of the EFS Security Group'
    Value: !Ref EFSSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-EFS-SG-ID'

  LambdaSecurityGroupId:
    Description: 'ID of the Lambda Security Group'
    Value: !Ref LambdaSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-Lambda-SG-ID'

  ECSSecurityGroupId:
    Description: 'ID of the ECS Security Group'
    Value: !Ref ECSSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-ECS-SG-ID'